name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # oder master, je nach deinem Hauptbranch
  pull_request:
    branches:
      - main  # oder master, je nach deinem Hauptbranch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js (optional, falls du noch Node.js für Build-Schritte verwendest)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build your project (optional, falls du ein Build-System wie z.B. webpack verwendest)
      run: |
        npm install
        npm run build  # Falls du einen Build-Prozess hast

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Der Branch, auf dem die Seite gehostet wird
        folder: ./  # Der Ordner, in dem sich die index.html befindet
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token für Berechtigungen
